# Generated by Django 4.0.3 on 2022-11-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_tag_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers',
        ),
    ]
