# Generated by Django 4.0.3 on 2022-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_avatar_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profiles/avatars/'),
        ),
    ]
